export const ADD_USER_INTERESTS = 'ADD_USER_INTERESTS';
export const ADD_USER_INTERESTS_LOADING = 'ADD_USER_INTERESTS_LOADING';
export const ADD_USER_INTERESTS_SUCCESS = 'ADD_USER_INTERESTS_SUCCESS';
export const ADD_USER_INTERESTS_FAIL = 'ADD_USER_INTERESTS_FAIL';
