export const GET_USER_EVENTS = 'GET_USER_EVENTS';
export const GET_USER_EVENTS_LOADING = 'ADD_EVENT_TO_PARTICIPATED_LOADING';
export const GET_USER_EVENTS_SUCCESS = 'ADD_EVENT_TO_PARTICIPATED_SUCCESS';
export const GET_USER_EVENTS_FAIL = 'ADD_EVENT_TO_PARTICIPATED_FAIL';
