const actions = {
	FETCH_ALL_QUESTIONNAIRES: 'FETCH_ALL_QUESTIONNAIRES',
	FETCH_ALL_QUESTIONNAIRES_FAILED: 'FETCH_ALL_QUESTIONNAIRES_FAILED',
	FETCH_USER_QUESTIONNAIRE: 'FETCH_USER_QUESTIONNAIRES',
	ANSWER_QUESTIONNAIRE: 'ANSWER_QUESTIONNAIRE',
};
export default actions;
