const actions = {
	FETCH_ALL_QUESTIONNAIRES: 'FETCH_ALL_QUESTIONNAIRES',
	FETCH_ALL_QUESTIONNAIRES_FAILED: 'FETCH_ALL_QUESTIONNAIRES_FAILED',
	FETCH_USER_QUESTIONNAIRE: 'FETCH_USER_QUESTIONNAIRES',
	ANSWER_QUESTION: 'ANSWER_QUESTION',
	PARTICIPATE_TO_QUESTIONNAIRE: 'PARTICIPATE_TO_QUESTIONNAIRE',
};
export default actions;
