const actions = {
	FETCH_MY_PARTICIPATED_EVENT: 'FETCH_MY_PARTICIPATED_EVENT',
	ADD_EVENT_TO_MY_PARTICIPATED_LIST: 'ADD_EVENT_TO_MY_PARTICIPATED_LIST',
	ADD_EVENT_TO_MY_PARTICIPATED_LIST_FAIL: 'ADD_EVENT_TO_MY_PARTICIPATED_LIST_FAIL',
};
export default actions;
