export const ADD_EVENT_TO_PARTICIPATED = 'ADD_EVENT_TO_PARTICIPATED';
export const RESET_EVENT_TO_PARTICIPATED_STATE = 'RESET_EVENT_TO_PARTICIPATED_STATE';
export const ADD_EVENT_TO_PARTICIPATED_LOADING = 'ADD_EVENT_TO_PARTICIPATED_LOADING';
export const ADD_EVENT_TO_PARTICIPATED_SUCCESS = 'ADD_EVENT_TO_PARTICIPATED_SUCCESS';
export const ADD_EVENT_TO_PARTICIPATED_FAIL = 'ADD_EVENT_TO_PARTICIPATED_FAIL';